/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ce8e0bc6-5d91-422d-8059-9d2c2d4326b6",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Q0BTMHYhg",
    "aws_user_pools_web_client_id": "5ap1avv25jdjusliqa87dbuoot",
    "oauth": {}
};


export default awsmobile;
