/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ce8e0bc6-5d91-422d-8059-9d2c2d4326b6",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Q0BTMHYhg",
    "aws_user_pools_web_client_id": "5ap1avv25jdjusliqa87dbuoot",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://qxxwjtwg45chzc6ameazn3odyi.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vwesdv35wjcx3ecjmk2oveldv4",
    "aws_user_files_s3_bucket": "vicbucket150028-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
